### ISSUE TITLE
Creating code with 'cargo generate rksm/axum-yew-template' doesnt run

### ISSUE THREAD

**Issue by deanchalk** [rksm/axum-yew-setup#10]
Hi

Sorry if Ive made some mistakes or incorreect assumptions, Im new to rust programming, but it looks like this cargo generate command (cargo generate rksm/axum-yew-template) creates files that dont build or run.

1) They reference axum_extra::routing::SpaRouter which no longer exists
2) pushd frontend; in file install-dependencies.sh creates an error - but changing it to pushd ../'frontend'; seems to work. Same for pushd server
3) The code seems very different from the code that's actually in the source repo - does the cargo generate command need updating?

This is exactly the code I need to get started on my axum / yew first project - so hopefully I can get things running

Do you recommend I just clone the repo and start there?

Many thanks

**Comment by rksm** [comment]
Hi, indeed, this is confusing. I'll update the template repo and yes, just cloning this repository should be a good starting point.

Thanks!
