### ISSUE TITLE
port number typo?

### ISSUE THREAD

**Issue by matthiasdebernardini** [rksm/axum-yew-setup#4]
Is the port number a typo? I'm trying different stuff but I can't get it to work. I'm running this in digitalocean remotely.

I'm trying to understand if there is something under the hood where the port number changes or something. I am assuming you changed it because the port was still busy when you were developing?

Unsure, but some help would be useful. 

Thank you for the blog, it's exactly what I was looking for to get started.

```
Now let’s test it! Start the server on port 8081 and the frontend in dev mode with a proxy for api requests:

cargo run --bin server -- --port 8081
cd frontend; trunk serve --proxy-backend=http://[::1]:8081/api/
When you open your web browser at [localhost:8080/hello-server](http://localhost:8080/hello-server) you should now see:
```

**Comment by matthiasdebernardini** [comment]
my problem is probably unrelated to the port number but I figured I could bring it up

**Comment by matthiasdebernardini** [comment]
I did eventually get it to work, but I had to skip that part of the tutorial. Thanks again!

**Comment by rksm** [comment]
Hi! So the dev setup presented at https://robert.kra.hn/posts/2022-04-03_rust-web-wasm/ is as follows:

1. You start the axum server on part 8081 but don't use it directly.
2. You start trunk as normal (it will default to port 8080) but tell it to use a proxy backend that runs on port 8081

The effect of this is that trunk will serve the static files and will take care of reloading your app when you make changes.
For everything else, it will fallback to the axum server that can provide an API or some sort of server logic.

For prod you just start the axum server, on port 8080 this time. This means that in terms of using the app you don't need to switch ports around depending on dev or release mode.
